### ISSUE TITLE
Linear features partially disappear when hovered over

### ISSUE THREAD

**Issue by csm2023** [facebook/Rapid#1614]
### Description

When hovering over linear features, sometimes they will partially (or entirely) become invisible. Panning the map and then hovering again over the same feature changes how much is visible. 

### Screenshots

[Screen Recording 2024-11-18 at 12.26.02 PM.zip](https://github.com/user-attachments/files/17805415/Screen.Recording.2024-11-18.at.12.26.02.PM.zip)

### Version

2.5.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Chrome v131.0

### The OS you're using

mac

### Steps to reproduce

1. Open RapID
2. Hover over linear features

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid/pull-request-1583/index.html#map=20.20/30.38630/-81.65577&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Thanks for reporting!  I've see a few people report parts of the map disappear around where the glow is supposed to be.

https://github.com/user-attachments/assets/f0ff4b20-7337-41a7-92ff-6717376136f7

There's a possibility that an upcoming version of Pixi might fix this - I'll post something here once it's landed in the canary build and we can check!
https://github.com/pixijs/pixijs/pull/11058

**Comment by csm2023** [comment]
> Anyone who ran into this issue before, can you please test in canary and let me know if it's still an issue? Thanks! https://rapideditor.org/canary

I've just tested it using the link you posted. On my end, the issue is resolved! Looks much better :) Thanks for looking into it

**Comment by bhousel** [comment]
Thanks for testing @csm2023 , I'll close the issue for now, but can reopen if other people are still seeing it.  👍
